// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: payfi/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryAllPaymentsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPaymentsRequest) Reset()         { *m = QueryAllPaymentsRequest{} }
func (m *QueryAllPaymentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPaymentsRequest) ProtoMessage()    {}
func (*QueryAllPaymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{2}
}
func (m *QueryAllPaymentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPaymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPaymentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPaymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPaymentsRequest.Merge(m, src)
}
func (m *QueryAllPaymentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPaymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPaymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPaymentsRequest proto.InternalMessageInfo

func (m *QueryAllPaymentsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPaymentsResponse struct {
	Payments   []*Payment          `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPaymentsResponse) Reset()         { *m = QueryAllPaymentsResponse{} }
func (m *QueryAllPaymentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPaymentsResponse) ProtoMessage()    {}
func (*QueryAllPaymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{3}
}
func (m *QueryAllPaymentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPaymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPaymentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPaymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPaymentsResponse.Merge(m, src)
}
func (m *QueryAllPaymentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPaymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPaymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPaymentsResponse proto.InternalMessageInfo

func (m *QueryAllPaymentsResponse) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func (m *QueryAllPaymentsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryPaymentRequest struct {
	PaymentId       uint64 `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	MerchantAddress string `protobuf:"bytes,2,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
}

func (m *QueryPaymentRequest) Reset()         { *m = QueryPaymentRequest{} }
func (m *QueryPaymentRequest) String() string { return proto.CompactTextString(m) }
func (*QueryPaymentRequest) ProtoMessage()    {}
func (*QueryPaymentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{4}
}
func (m *QueryPaymentRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPaymentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPaymentRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPaymentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPaymentRequest.Merge(m, src)
}
func (m *QueryPaymentRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryPaymentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPaymentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPaymentRequest proto.InternalMessageInfo

func (m *QueryPaymentRequest) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *QueryPaymentRequest) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

type QueryPaymentResponse struct {
	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
}

func (m *QueryPaymentResponse) Reset()         { *m = QueryPaymentResponse{} }
func (m *QueryPaymentResponse) String() string { return proto.CompactTextString(m) }
func (*QueryPaymentResponse) ProtoMessage()    {}
func (*QueryPaymentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{5}
}
func (m *QueryPaymentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryPaymentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryPaymentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryPaymentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryPaymentResponse.Merge(m, src)
}
func (m *QueryPaymentResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryPaymentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryPaymentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryPaymentResponse proto.InternalMessageInfo

func (m *QueryPaymentResponse) GetPayment() *Payment {
	if m != nil {
		return m.Payment
	}
	return nil
}

type QueryMerchantPaymentsRequest struct {
	MerchantAddress string             `protobuf:"bytes,1,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	Pagination      *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMerchantPaymentsRequest) Reset()         { *m = QueryMerchantPaymentsRequest{} }
func (m *QueryMerchantPaymentsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMerchantPaymentsRequest) ProtoMessage()    {}
func (*QueryMerchantPaymentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{6}
}
func (m *QueryMerchantPaymentsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerchantPaymentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerchantPaymentsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerchantPaymentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerchantPaymentsRequest.Merge(m, src)
}
func (m *QueryMerchantPaymentsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerchantPaymentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerchantPaymentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerchantPaymentsRequest proto.InternalMessageInfo

func (m *QueryMerchantPaymentsRequest) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

func (m *QueryMerchantPaymentsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMerchantPaymentsResponse struct {
	Payments   []*Payment          `protobuf:"bytes,1,rep,name=payments,proto3" json:"payments,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMerchantPaymentsResponse) Reset()         { *m = QueryMerchantPaymentsResponse{} }
func (m *QueryMerchantPaymentsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMerchantPaymentsResponse) ProtoMessage()    {}
func (*QueryMerchantPaymentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{7}
}
func (m *QueryMerchantPaymentsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerchantPaymentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerchantPaymentsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerchantPaymentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerchantPaymentsResponse.Merge(m, src)
}
func (m *QueryMerchantPaymentsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerchantPaymentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerchantPaymentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerchantPaymentsResponse proto.InternalMessageInfo

func (m *QueryMerchantPaymentsResponse) GetPayments() []*Payment {
	if m != nil {
		return m.Payments
	}
	return nil
}

func (m *QueryMerchantPaymentsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMerchantRevenueRequest struct {
	MerchantAddress string `protobuf:"bytes,1,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
}

func (m *QueryMerchantRevenueRequest) Reset()         { *m = QueryMerchantRevenueRequest{} }
func (m *QueryMerchantRevenueRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMerchantRevenueRequest) ProtoMessage()    {}
func (*QueryMerchantRevenueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{8}
}
func (m *QueryMerchantRevenueRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerchantRevenueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerchantRevenueRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerchantRevenueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerchantRevenueRequest.Merge(m, src)
}
func (m *QueryMerchantRevenueRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerchantRevenueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerchantRevenueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerchantRevenueRequest proto.InternalMessageInfo

func (m *QueryMerchantRevenueRequest) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

type QueryMerchantRevenueResponse struct {
	Revenue *MerchantRevenue `protobuf:"bytes,1,opt,name=revenue,proto3" json:"revenue,omitempty"`
}

func (m *QueryMerchantRevenueResponse) Reset()         { *m = QueryMerchantRevenueResponse{} }
func (m *QueryMerchantRevenueResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMerchantRevenueResponse) ProtoMessage()    {}
func (*QueryMerchantRevenueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{9}
}
func (m *QueryMerchantRevenueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerchantRevenueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerchantRevenueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerchantRevenueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerchantRevenueResponse.Merge(m, src)
}
func (m *QueryMerchantRevenueResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerchantRevenueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerchantRevenueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerchantRevenueResponse proto.InternalMessageInfo

func (m *QueryMerchantRevenueResponse) GetRevenue() *MerchantRevenue {
	if m != nil {
		return m.Revenue
	}
	return nil
}

type QueryMerchantRequest struct {
	MerchantAddress string `protobuf:"bytes,1,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
}

func (m *QueryMerchantRequest) Reset()         { *m = QueryMerchantRequest{} }
func (m *QueryMerchantRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMerchantRequest) ProtoMessage()    {}
func (*QueryMerchantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{10}
}
func (m *QueryMerchantRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerchantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerchantRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerchantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerchantRequest.Merge(m, src)
}
func (m *QueryMerchantRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerchantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerchantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerchantRequest proto.InternalMessageInfo

func (m *QueryMerchantRequest) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

type QueryMerchantResponse struct {
	Merchant *Merchant `protobuf:"bytes,1,opt,name=merchant,proto3" json:"merchant,omitempty"`
}

func (m *QueryMerchantResponse) Reset()         { *m = QueryMerchantResponse{} }
func (m *QueryMerchantResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMerchantResponse) ProtoMessage()    {}
func (*QueryMerchantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{11}
}
func (m *QueryMerchantResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMerchantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMerchantResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMerchantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMerchantResponse.Merge(m, src)
}
func (m *QueryMerchantResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMerchantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMerchantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMerchantResponse proto.InternalMessageInfo

func (m *QueryMerchantResponse) GetMerchant() *Merchant {
	if m != nil {
		return m.Merchant
	}
	return nil
}

type QueryAllMerchantsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMerchantsRequest) Reset()         { *m = QueryAllMerchantsRequest{} }
func (m *QueryAllMerchantsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllMerchantsRequest) ProtoMessage()    {}
func (*QueryAllMerchantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{12}
}
func (m *QueryAllMerchantsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMerchantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMerchantsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMerchantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMerchantsRequest.Merge(m, src)
}
func (m *QueryAllMerchantsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMerchantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMerchantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMerchantsRequest proto.InternalMessageInfo

func (m *QueryAllMerchantsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllMerchantsResponse struct {
	Merchants  []*Merchant         `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllMerchantsResponse) Reset()         { *m = QueryAllMerchantsResponse{} }
func (m *QueryAllMerchantsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllMerchantsResponse) ProtoMessage()    {}
func (*QueryAllMerchantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{13}
}
func (m *QueryAllMerchantsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllMerchantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllMerchantsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllMerchantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllMerchantsResponse.Merge(m, src)
}
func (m *QueryAllMerchantsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllMerchantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllMerchantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllMerchantsResponse proto.InternalMessageInfo

func (m *QueryAllMerchantsResponse) GetMerchants() []*Merchant {
	if m != nil {
		return m.Merchants
	}
	return nil
}

func (m *QueryAllMerchantsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRevenueRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRevenueRequest) Reset()         { *m = QueryAllRevenueRequest{} }
func (m *QueryAllRevenueRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRevenueRequest) ProtoMessage()    {}
func (*QueryAllRevenueRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{14}
}
func (m *QueryAllRevenueRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRevenueRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRevenueRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRevenueRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRevenueRequest.Merge(m, src)
}
func (m *QueryAllRevenueRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRevenueRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRevenueRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRevenueRequest proto.InternalMessageInfo

func (m *QueryAllRevenueRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRevenueResponse struct {
	Revenues   []*MerchantRevenue  `protobuf:"bytes,1,rep,name=revenues,proto3" json:"revenues,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRevenueResponse) Reset()         { *m = QueryAllRevenueResponse{} }
func (m *QueryAllRevenueResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRevenueResponse) ProtoMessage()    {}
func (*QueryAllRevenueResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0fad88d52e9028c2, []int{15}
}
func (m *QueryAllRevenueResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRevenueResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRevenueResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRevenueResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRevenueResponse.Merge(m, src)
}
func (m *QueryAllRevenueResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRevenueResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRevenueResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRevenueResponse proto.InternalMessageInfo

func (m *QueryAllRevenueResponse) GetRevenues() []*MerchantRevenue {
	if m != nil {
		return m.Revenues
	}
	return nil
}

func (m *QueryAllRevenueResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "kiichain.kiichain3.payfi.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "kiichain.kiichain3.payfi.QueryParamsResponse")
	proto.RegisterType((*QueryAllPaymentsRequest)(nil), "kiichain.kiichain3.payfi.QueryAllPaymentsRequest")
	proto.RegisterType((*QueryAllPaymentsResponse)(nil), "kiichain.kiichain3.payfi.QueryAllPaymentsResponse")
	proto.RegisterType((*QueryPaymentRequest)(nil), "kiichain.kiichain3.payfi.QueryPaymentRequest")
	proto.RegisterType((*QueryPaymentResponse)(nil), "kiichain.kiichain3.payfi.QueryPaymentResponse")
	proto.RegisterType((*QueryMerchantPaymentsRequest)(nil), "kiichain.kiichain3.payfi.QueryMerchantPaymentsRequest")
	proto.RegisterType((*QueryMerchantPaymentsResponse)(nil), "kiichain.kiichain3.payfi.QueryMerchantPaymentsResponse")
	proto.RegisterType((*QueryMerchantRevenueRequest)(nil), "kiichain.kiichain3.payfi.QueryMerchantRevenueRequest")
	proto.RegisterType((*QueryMerchantRevenueResponse)(nil), "kiichain.kiichain3.payfi.QueryMerchantRevenueResponse")
	proto.RegisterType((*QueryMerchantRequest)(nil), "kiichain.kiichain3.payfi.QueryMerchantRequest")
	proto.RegisterType((*QueryMerchantResponse)(nil), "kiichain.kiichain3.payfi.QueryMerchantResponse")
	proto.RegisterType((*QueryAllMerchantsRequest)(nil), "kiichain.kiichain3.payfi.QueryAllMerchantsRequest")
	proto.RegisterType((*QueryAllMerchantsResponse)(nil), "kiichain.kiichain3.payfi.QueryAllMerchantsResponse")
	proto.RegisterType((*QueryAllRevenueRequest)(nil), "kiichain.kiichain3.payfi.QueryAllRevenueRequest")
	proto.RegisterType((*QueryAllRevenueResponse)(nil), "kiichain.kiichain3.payfi.QueryAllRevenueResponse")
}

func init() { proto.RegisterFile("payfi/query.proto", fileDescriptor_0fad88d52e9028c2) }

var fileDescriptor_0fad88d52e9028c2 = []byte{
	// 838 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x97, 0x4b, 0x6f, 0xd3, 0x4a,
	0x14, 0xc7, 0x33, 0xbd, 0xbd, 0x6d, 0x7a, 0x7a, 0xa5, 0xf6, 0xce, 0xed, 0x85, 0x60, 0xda, 0x90,
	0x1a, 0x68, 0x93, 0x3e, 0x6c, 0x92, 0x88, 0xb2, 0x40, 0x20, 0x5a, 0x54, 0x1e, 0x0b, 0xa4, 0x12,
	0x84, 0x90, 0xd8, 0x84, 0x49, 0x62, 0x52, 0x8b, 0xc4, 0x76, 0x63, 0xa7, 0x22, 0x5b, 0xbe, 0x00,
	0xa0, 0x2e, 0xd8, 0x22, 0x84, 0x78, 0xec, 0x58, 0xb0, 0xe0, 0x23, 0x74, 0x59, 0x89, 0x0d, 0x2b,
	0x84, 0x5a, 0x3e, 0x08, 0xca, 0xcc, 0xb1, 0x93, 0xb8, 0x79, 0xd8, 0x28, 0x0b, 0x76, 0xd6, 0xc9,
	0xf9, 0x9f, 0xf3, 0x9b, 0xff, 0xcc, 0x9c, 0x51, 0xe0, 0x5f, 0x8b, 0x35, 0x1e, 0xeb, 0xea, 0x4e,
	0x5d, 0xab, 0x35, 0x14, 0xab, 0x66, 0x3a, 0x26, 0x8d, 0x3d, 0xd1, 0xf5, 0xe2, 0x36, 0xd3, 0x0d,
	0xc5, 0xfd, 0xc8, 0x2a, 0x3c, 0x4b, 0x5a, 0x2a, 0x9a, 0x76, 0xd5, 0xb4, 0xd5, 0x02, 0xb3, 0x35,
	0x21, 0x51, 0x77, 0xd3, 0x05, 0xcd, 0x61, 0x69, 0xd5, 0x62, 0x65, 0xdd, 0x60, 0x8e, 0x6e, 0x1a,
	0xa2, 0x8a, 0x34, 0x53, 0x36, 0xcb, 0x26, 0xff, 0x54, 0x9b, 0x5f, 0x18, 0x9d, 0x2d, 0x9b, 0x66,
	0xb9, 0xa2, 0xa9, 0xcc, 0xd2, 0x55, 0x66, 0x18, 0xa6, 0xc3, 0x25, 0x36, 0xfe, 0x4a, 0x05, 0x8c,
	0xc5, 0x6a, 0xac, 0xea, 0xc6, 0x10, 0xd0, 0x69, 0x58, 0x1a, 0x86, 0xe4, 0x19, 0xa0, 0x77, 0x9b,
	0xcd, 0xb7, 0x78, 0x5e, 0x4e, 0xdb, 0xa9, 0x6b, 0xb6, 0x23, 0xdf, 0x87, 0xff, 0x3a, 0xa2, 0xb6,
	0x65, 0x1a, 0xb6, 0x46, 0xaf, 0xc2, 0x98, 0xa8, 0x17, 0x23, 0x09, 0x92, 0x9c, 0xcc, 0x24, 0x94,
	0x5e, 0xcb, 0x53, 0x84, 0x72, 0x63, 0x74, 0xff, 0xfb, 0x99, 0x48, 0x0e, 0x55, 0x32, 0x83, 0x93,
	0xbc, 0xec, 0x7a, 0xa5, 0xb2, 0xc5, 0x1a, 0x55, 0xcd, 0x70, 0xdc, 0x8e, 0xf4, 0x06, 0x40, 0x6b,
	0xd9, 0x58, 0x7e, 0x41, 0x11, 0x1e, 0x29, 0x4d, 0x8f, 0x14, 0x61, 0x2b, 0x7a, 0xa4, 0x6c, 0xb1,
	0xb2, 0x86, 0xda, 0x5c, 0x9b, 0x52, 0x7e, 0x43, 0x20, 0x76, 0xbc, 0x07, 0xf2, 0x5f, 0x81, 0xa8,
	0x85, 0xb1, 0x18, 0x49, 0xfc, 0x95, 0x9c, 0xcc, 0xcc, 0xf7, 0x5b, 0x01, 0xcf, 0xcc, 0x79, 0x12,
	0x7a, 0xb3, 0x83, 0x71, 0x84, 0x33, 0x2e, 0x0e, 0x64, 0x14, 0xbd, 0x3b, 0x20, 0xf3, 0x9e, 0xbd,
	0xa2, 0x05, 0x7a, 0x30, 0xd7, 0xac, 0xcf, 0x23, 0x79, 0xbd, 0xc4, 0x3d, 0x18, 0xcd, 0x4d, 0x60,
	0xe4, 0x76, 0x89, 0xa6, 0x60, 0xba, 0xaa, 0xd5, 0x8a, 0xdb, 0xcc, 0x70, 0xf2, 0xac, 0x54, 0xaa,
	0x69, 0xb6, 0xcd, 0x21, 0x26, 0x72, 0x53, 0x6e, 0x7c, 0x5d, 0x84, 0xe5, 0x7b, 0x30, 0xd3, 0xd9,
	0x00, 0x0d, 0xb8, 0x0c, 0xe3, 0x58, 0x0f, 0x2d, 0x0e, 0xb0, 0x7e, 0x57, 0x21, 0xbf, 0x24, 0x30,
	0xcb, 0xab, 0xde, 0xc1, 0x6e, 0xfe, 0x3d, 0xec, 0x06, 0x48, 0xba, 0x02, 0xfa, 0xb6, 0x7b, 0xe4,
	0xb7, 0xb7, 0xfb, 0x3d, 0x81, 0xb9, 0x1e, 0x4c, 0x7f, 0xd8, 0x9e, 0xdf, 0x82, 0xd3, 0x1d, 0xa0,
	0x39, 0x6d, 0x57, 0x33, 0xea, 0x5a, 0x78, 0xef, 0xe4, 0xa2, 0x6f, 0x1b, 0xbc, 0x4a, 0xb8, 0xe2,
	0xeb, 0x30, 0x5e, 0x13, 0x21, 0xdc, 0xe4, 0x54, 0xef, 0x05, 0xfb, 0x6b, 0xb8, 0x4a, 0x79, 0x1d,
	0x4f, 0x50, 0x2b, 0x21, 0x34, 0xe7, 0x03, 0xf8, 0xdf, 0x57, 0xc2, 0x1b, 0x23, 0x51, 0x37, 0x17,
	0x09, 0xe5, 0x00, 0x84, 0x9e, 0x46, 0x2e, 0xb4, 0xae, 0xb8, 0xfb, 0xeb, 0xd0, 0xe7, 0xc8, 0x3b,
	0x02, 0xa7, 0xba, 0x34, 0xc1, 0x15, 0x5c, 0x83, 0x09, 0x97, 0xc6, 0x3d, 0x55, 0x41, 0x96, 0xd0,
	0x12, 0x0d, 0xef, 0x5c, 0x3d, 0x82, 0x13, 0x2e, 0xa7, 0xef, 0x48, 0x0d, 0xcb, 0x8a, 0x8f, 0xa4,
	0x35, 0xb6, 0xfd, 0x67, 0x6d, 0x13, 0xa2, 0x78, 0x62, 0x5c, 0x1f, 0x42, 0x1c, 0x36, 0x4f, 0x3a,
	0x34, 0x37, 0x32, 0x9f, 0x00, 0xfe, 0xe6, 0xac, 0xf4, 0x39, 0x81, 0x31, 0xf1, 0x08, 0xd1, 0x95,
	0xde, 0x48, 0xc7, 0xdf, 0x3e, 0x69, 0x35, 0x60, 0xb6, 0xe8, 0x2e, 0x27, 0x9f, 0x7d, 0xfd, 0xb9,
	0x37, 0x22, 0xd3, 0x84, 0xea, 0x66, 0x7b, 0x1f, 0x59, 0xb5, 0xfd, 0x0d, 0xa6, 0x6f, 0x09, 0x4c,
	0xb6, 0xbd, 0x4a, 0x34, 0x3d, 0xa0, 0xd1, 0xf1, 0x57, 0x52, 0xca, 0x84, 0x91, 0x20, 0xa0, 0xc2,
	0x01, 0x93, 0x74, 0xa1, 0x37, 0x20, 0xab, 0x54, 0xf2, 0xde, 0xc4, 0xdb, 0x23, 0x30, 0x8e, 0x45,
	0xe8, 0x60, 0x2f, 0xda, 0x1f, 0x30, 0x49, 0x09, 0x9a, 0x8e, 0x68, 0x29, 0x8e, 0x76, 0x96, 0xce,
	0xf7, 0xf3, 0x4e, 0x90, 0x7c, 0x21, 0x30, 0xed, 0x9f, 0xf1, 0x74, 0x6d, 0x40, 0xbf, 0x1e, 0x0f,
	0x95, 0x74, 0x29, 0xb4, 0x0e, 0x81, 0xb3, 0x1c, 0x78, 0x95, 0x2e, 0xf7, 0x06, 0xf6, 0xa6, 0xa3,
	0x67, 0xe8, 0x67, 0x02, 0x53, 0xbe, 0xa3, 0x4f, 0x2f, 0x06, 0x24, 0xe8, 0xbc, 0xd2, 0xd2, 0x5a,
	0x58, 0x19, 0x72, 0x67, 0x38, 0xf7, 0x0a, 0x5d, 0x0a, 0xc0, 0x8d, 0x97, 0x92, 0xbe, 0x22, 0x10,
	0x75, 0xeb, 0x51, 0x25, 0x70, 0x63, 0x01, 0xaa, 0x06, 0xce, 0x47, 0xc2, 0x25, 0x4e, 0x78, 0x8e,
	0xca, 0x83, 0x09, 0xe9, 0x07, 0x02, 0xff, 0xb4, 0x8f, 0x65, 0x1a, 0xe0, 0x5a, 0xf8, 0x1f, 0x0a,
	0x29, 0x1b, 0x4a, 0x83, 0x94, 0x2a, 0xa7, 0x4c, 0xd1, 0xc5, 0xfe, 0x77, 0xa9, 0x35, 0xe6, 0x5f,
	0x13, 0x80, 0xd6, 0xd8, 0xa4, 0x17, 0x06, 0x37, 0xf5, 0xed, 0x78, 0x3a, 0x84, 0x02, 0x21, 0x57,
	0x39, 0xe4, 0x22, 0x3d, 0xdf, 0x1f, 0x12, 0xf7, 0x79, 0x63, 0x73, 0xff, 0x30, 0x4e, 0x0e, 0x0e,
	0xe3, 0xe4, 0xc7, 0x61, 0x9c, 0xbc, 0x38, 0x8a, 0x47, 0x0e, 0x8e, 0xe2, 0x91, 0x6f, 0x47, 0xf1,
	0xc8, 0xc3, 0xe5, 0xb2, 0xee, 0x6c, 0xd7, 0x0b, 0x4a, 0xd1, 0xac, 0x76, 0x2b, 0xf5, 0x54, 0x6d,
	0xfb, 0x3b, 0x51, 0x18, 0xe3, 0xff, 0x27, 0xb2, 0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf0, 0x8a,
	0xc3, 0x32, 0x05, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	AllPayments(ctx context.Context, in *QueryAllPaymentsRequest, opts ...grpc.CallOption) (*QueryAllPaymentsResponse, error)
	Payment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentResponse, error)
	MerchantPayments(ctx context.Context, in *QueryMerchantPaymentsRequest, opts ...grpc.CallOption) (*QueryMerchantPaymentsResponse, error)
	MerchantRevenue(ctx context.Context, in *QueryMerchantRevenueRequest, opts ...grpc.CallOption) (*QueryMerchantRevenueResponse, error)
	Merchant(ctx context.Context, in *QueryMerchantRequest, opts ...grpc.CallOption) (*QueryMerchantResponse, error)
	AllMerchants(ctx context.Context, in *QueryAllMerchantsRequest, opts ...grpc.CallOption) (*QueryAllMerchantsResponse, error)
	AllRevenue(ctx context.Context, in *QueryAllRevenueRequest, opts ...grpc.CallOption) (*QueryAllRevenueResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/kiichain.kiichain3.payfi.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllPayments(ctx context.Context, in *QueryAllPaymentsRequest, opts ...grpc.CallOption) (*QueryAllPaymentsResponse, error) {
	out := new(QueryAllPaymentsResponse)
	err := c.cc.Invoke(ctx, "/kiichain.kiichain3.payfi.Query/AllPayments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Payment(ctx context.Context, in *QueryPaymentRequest, opts ...grpc.CallOption) (*QueryPaymentResponse, error) {
	out := new(QueryPaymentResponse)
	err := c.cc.Invoke(ctx, "/kiichain.kiichain3.payfi.Query/Payment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MerchantPayments(ctx context.Context, in *QueryMerchantPaymentsRequest, opts ...grpc.CallOption) (*QueryMerchantPaymentsResponse, error) {
	out := new(QueryMerchantPaymentsResponse)
	err := c.cc.Invoke(ctx, "/kiichain.kiichain3.payfi.Query/MerchantPayments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MerchantRevenue(ctx context.Context, in *QueryMerchantRevenueRequest, opts ...grpc.CallOption) (*QueryMerchantRevenueResponse, error) {
	out := new(QueryMerchantRevenueResponse)
	err := c.cc.Invoke(ctx, "/kiichain.kiichain3.payfi.Query/MerchantRevenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Merchant(ctx context.Context, in *QueryMerchantRequest, opts ...grpc.CallOption) (*QueryMerchantResponse, error) {
	out := new(QueryMerchantResponse)
	err := c.cc.Invoke(ctx, "/kiichain.kiichain3.payfi.Query/Merchant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllMerchants(ctx context.Context, in *QueryAllMerchantsRequest, opts ...grpc.CallOption) (*QueryAllMerchantsResponse, error) {
	out := new(QueryAllMerchantsResponse)
	err := c.cc.Invoke(ctx, "/kiichain.kiichain3.payfi.Query/AllMerchants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) AllRevenue(ctx context.Context, in *QueryAllRevenueRequest, opts ...grpc.CallOption) (*QueryAllRevenueResponse, error) {
	out := new(QueryAllRevenueResponse)
	err := c.cc.Invoke(ctx, "/kiichain.kiichain3.payfi.Query/AllRevenue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	AllPayments(context.Context, *QueryAllPaymentsRequest) (*QueryAllPaymentsResponse, error)
	Payment(context.Context, *QueryPaymentRequest) (*QueryPaymentResponse, error)
	MerchantPayments(context.Context, *QueryMerchantPaymentsRequest) (*QueryMerchantPaymentsResponse, error)
	MerchantRevenue(context.Context, *QueryMerchantRevenueRequest) (*QueryMerchantRevenueResponse, error)
	Merchant(context.Context, *QueryMerchantRequest) (*QueryMerchantResponse, error)
	AllMerchants(context.Context, *QueryAllMerchantsRequest) (*QueryAllMerchantsResponse, error)
	AllRevenue(context.Context, *QueryAllRevenueRequest) (*QueryAllRevenueResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) AllPayments(ctx context.Context, req *QueryAllPaymentsRequest) (*QueryAllPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllPayments not implemented")
}
func (*UnimplementedQueryServer) Payment(ctx context.Context, req *QueryPaymentRequest) (*QueryPaymentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Payment not implemented")
}
func (*UnimplementedQueryServer) MerchantPayments(ctx context.Context, req *QueryMerchantPaymentsRequest) (*QueryMerchantPaymentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantPayments not implemented")
}
func (*UnimplementedQueryServer) MerchantRevenue(ctx context.Context, req *QueryMerchantRevenueRequest) (*QueryMerchantRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MerchantRevenue not implemented")
}
func (*UnimplementedQueryServer) Merchant(ctx context.Context, req *QueryMerchantRequest) (*QueryMerchantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Merchant not implemented")
}
func (*UnimplementedQueryServer) AllMerchants(ctx context.Context, req *QueryAllMerchantsRequest) (*QueryAllMerchantsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllMerchants not implemented")
}
func (*UnimplementedQueryServer) AllRevenue(ctx context.Context, req *QueryAllRevenueRequest) (*QueryAllRevenueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllRevenue not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiichain.kiichain3.payfi.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiichain.kiichain3.payfi.Query/AllPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllPayments(ctx, req.(*QueryAllPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Payment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Payment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiichain.kiichain3.payfi.Query/Payment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Payment(ctx, req.(*QueryPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MerchantPayments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMerchantPaymentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MerchantPayments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiichain.kiichain3.payfi.Query/MerchantPayments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MerchantPayments(ctx, req.(*QueryMerchantPaymentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MerchantRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMerchantRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MerchantRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiichain.kiichain3.payfi.Query/MerchantRevenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MerchantRevenue(ctx, req.(*QueryMerchantRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Merchant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMerchantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Merchant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiichain.kiichain3.payfi.Query/Merchant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Merchant(ctx, req.(*QueryMerchantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllMerchants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllMerchantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllMerchants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiichain.kiichain3.payfi.Query/AllMerchants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllMerchants(ctx, req.(*QueryAllMerchantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_AllRevenue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRevenueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).AllRevenue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kiichain.kiichain3.payfi.Query/AllRevenue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).AllRevenue(ctx, req.(*QueryAllRevenueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kiichain.kiichain3.payfi.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "AllPayments",
			Handler:    _Query_AllPayments_Handler,
		},
		{
			MethodName: "Payment",
			Handler:    _Query_Payment_Handler,
		},
		{
			MethodName: "MerchantPayments",
			Handler:    _Query_MerchantPayments_Handler,
		},
		{
			MethodName: "MerchantRevenue",
			Handler:    _Query_MerchantRevenue_Handler,
		},
		{
			MethodName: "Merchant",
			Handler:    _Query_Merchant_Handler,
		},
		{
			MethodName: "AllMerchants",
			Handler:    _Query_AllMerchants_Handler,
		},
		{
			MethodName: "AllRevenue",
			Handler:    _Query_AllRevenue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "payfi/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPaymentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPaymentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPaymentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPaymentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPaymentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPaymentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Payments) > 0 {
		for iNdEx := len(m.Payments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Payments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryPaymentRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPaymentRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPaymentRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.PaymentId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.PaymentId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryPaymentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryPaymentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryPaymentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Payment != nil {
		{
			size, err := m.Payment.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerchantPaymentsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerchantPaymentsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerchantPaymentsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerchantPaymentsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerchantPaymentsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerchantPaymentsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Payments) > 0 {
		for iNdEx := len(m.Payments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Payments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerchantRevenueRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerchantRevenueRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerchantRevenueRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerchantRevenueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerchantRevenueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerchantRevenueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Revenue != nil {
		{
			size, err := m.Revenue.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerchantRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerchantRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerchantRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMerchantResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMerchantResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMerchantResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Merchant != nil {
		{
			size, err := m.Merchant.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMerchantsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMerchantsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMerchantsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllMerchantsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllMerchantsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllMerchantsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Merchants) > 0 {
		for iNdEx := len(m.Merchants) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Merchants[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRevenueRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRevenueRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRevenueRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRevenueResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRevenueResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRevenueResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Revenues) > 0 {
		for iNdEx := len(m.Revenues) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Revenues[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPaymentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPaymentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Payments) > 0 {
		for _, e := range m.Payments {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPaymentRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PaymentId != 0 {
		n += 1 + sovQuery(uint64(m.PaymentId))
	}
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryPaymentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Payment != nil {
		l = m.Payment.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMerchantPaymentsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMerchantPaymentsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Payments) > 0 {
		for _, e := range m.Payments {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMerchantRevenueRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMerchantRevenueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Revenue != nil {
		l = m.Revenue.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMerchantRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMerchantResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Merchant != nil {
		l = m.Merchant.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMerchantsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllMerchantsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Merchants) > 0 {
		for _, e := range m.Merchants {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRevenueRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRevenueResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Revenues) > 0 {
		for _, e := range m.Revenues {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPaymentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPaymentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPaymentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPaymentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPaymentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPaymentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payments = append(m.Payments, &Payment{})
			if err := m.Payments[len(m.Payments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPaymentRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPaymentRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPaymentRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentId", wireType)
			}
			m.PaymentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaymentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryPaymentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryPaymentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryPaymentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Payment == nil {
				m.Payment = &Payment{}
			}
			if err := m.Payment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerchantPaymentsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerchantPaymentsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerchantPaymentsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerchantPaymentsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerchantPaymentsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerchantPaymentsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payments = append(m.Payments, &Payment{})
			if err := m.Payments[len(m.Payments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerchantRevenueRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerchantRevenueRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerchantRevenueRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerchantRevenueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerchantRevenueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerchantRevenueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revenue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Revenue == nil {
				m.Revenue = &MerchantRevenue{}
			}
			if err := m.Revenue.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerchantRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerchantRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerchantRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMerchantResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMerchantResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMerchantResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Merchant", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Merchant == nil {
				m.Merchant = &Merchant{}
			}
			if err := m.Merchant.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMerchantsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMerchantsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMerchantsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllMerchantsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllMerchantsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllMerchantsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Merchants", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Merchants = append(m.Merchants, &Merchant{})
			if err := m.Merchants[len(m.Merchants)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRevenueRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRevenueRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRevenueRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRevenueResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRevenueResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRevenueResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Revenues", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Revenues = append(m.Revenues, &MerchantRevenue{})
			if err := m.Revenues[len(m.Revenues)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
