// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: payfi/types.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Merchant represents a registered merchant in the system
type Merchant struct {
	MerchantAddress        string `protobuf:"bytes,1,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	CreatorAddress         string `protobuf:"bytes,2,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`
	BusinessName           string `protobuf:"bytes,3,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessAddress        string `protobuf:"bytes,4,opt,name=business_address,json=businessAddress,proto3" json:"business_address,omitempty"`
	BusinessPhone          string `protobuf:"bytes,5,opt,name=business_phone,json=businessPhone,proto3" json:"business_phone,omitempty"`
	BusinessEmail          string `protobuf:"bytes,6,opt,name=business_email,json=businessEmail,proto3" json:"business_email,omitempty"`
	BusinessDescription    string `protobuf:"bytes,7,opt,name=business_description,json=businessDescription,proto3" json:"business_description,omitempty"`
	KycStatus              bool   `protobuf:"varint,8,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
	KycTimestamp           int64  `protobuf:"varint,9,opt,name=kyc_timestamp,json=kycTimestamp,proto3" json:"kyc_timestamp,omitempty"`
	KycExpirationTimestamp int64  `protobuf:"varint,10,opt,name=kyc_expiration_timestamp,json=kycExpirationTimestamp,proto3" json:"kyc_expiration_timestamp,omitempty"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3a40c559a2ead8, []int{0}
}
func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return m.Size()
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

func (m *Merchant) GetCreatorAddress() string {
	if m != nil {
		return m.CreatorAddress
	}
	return ""
}

func (m *Merchant) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *Merchant) GetBusinessAddress() string {
	if m != nil {
		return m.BusinessAddress
	}
	return ""
}

func (m *Merchant) GetBusinessPhone() string {
	if m != nil {
		return m.BusinessPhone
	}
	return ""
}

func (m *Merchant) GetBusinessEmail() string {
	if m != nil {
		return m.BusinessEmail
	}
	return ""
}

func (m *Merchant) GetBusinessDescription() string {
	if m != nil {
		return m.BusinessDescription
	}
	return ""
}

func (m *Merchant) GetKycStatus() bool {
	if m != nil {
		return m.KycStatus
	}
	return false
}

func (m *Merchant) GetKycTimestamp() int64 {
	if m != nil {
		return m.KycTimestamp
	}
	return 0
}

func (m *Merchant) GetKycExpirationTimestamp() int64 {
	if m != nil {
		return m.KycExpirationTimestamp
	}
	return 0
}

// Merchant Revenue represents kpis and revenue data for a merchant
type MerchantRevenue struct {
	MerchantAddress string                                   `protobuf:"bytes,1,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	TotalPayments   uint64                                   `protobuf:"varint,2,opt,name=total_payments,json=totalPayments,proto3" json:"total_payments,omitempty"`
	TotalRevenue    github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,3,rep,name=total_revenue,json=totalRevenue,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"total_revenue"`
}

func (m *MerchantRevenue) Reset()         { *m = MerchantRevenue{} }
func (m *MerchantRevenue) String() string { return proto.CompactTextString(m) }
func (*MerchantRevenue) ProtoMessage()    {}
func (*MerchantRevenue) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3a40c559a2ead8, []int{1}
}
func (m *MerchantRevenue) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MerchantRevenue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MerchantRevenue.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MerchantRevenue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerchantRevenue.Merge(m, src)
}
func (m *MerchantRevenue) XXX_Size() int {
	return m.Size()
}
func (m *MerchantRevenue) XXX_DiscardUnknown() {
	xxx_messageInfo_MerchantRevenue.DiscardUnknown(m)
}

var xxx_messageInfo_MerchantRevenue proto.InternalMessageInfo

func (m *MerchantRevenue) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

func (m *MerchantRevenue) GetTotalPayments() uint64 {
	if m != nil {
		return m.TotalPayments
	}
	return 0
}

func (m *MerchantRevenue) GetTotalRevenue() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.TotalRevenue
	}
	return nil
}

// Payment represents a payment from a payer to a merchant
type Payment struct {
	PaymentId       uint64                                   `protobuf:"varint,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	PayerAddress    string                                   `protobuf:"bytes,2,opt,name=payer_address,json=payerAddress,proto3" json:"payer_address,omitempty"`
	MerchantAddress string                                   `protobuf:"bytes,3,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	Timestamp       int64                                    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Amount          github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,5,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3a40c559a2ead8, []int{2}
}
func (m *Payment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return m.Size()
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetPaymentId() uint64 {
	if m != nil {
		return m.PaymentId
	}
	return 0
}

func (m *Payment) GetPayerAddress() string {
	if m != nil {
		return m.PayerAddress
	}
	return ""
}

func (m *Payment) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

func (m *Payment) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Payment) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

func init() {
	proto.RegisterType((*Merchant)(nil), "kiichain.kiichain3.payfi.Merchant")
	proto.RegisterType((*MerchantRevenue)(nil), "kiichain.kiichain3.payfi.MerchantRevenue")
	proto.RegisterType((*Payment)(nil), "kiichain.kiichain3.payfi.Payment")
}

func init() { proto.RegisterFile("payfi/types.proto", fileDescriptor_dc3a40c559a2ead8) }

var fileDescriptor_dc3a40c559a2ead8 = []byte{
	// 544 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0x41, 0x6f, 0xd3, 0x30,
	0x14, 0x80, 0x1b, 0xd2, 0x75, 0xad, 0xe9, 0x5a, 0x08, 0x13, 0x32, 0x13, 0x64, 0x55, 0xd1, 0x44,
	0x11, 0x22, 0xa1, 0xf4, 0xc2, 0x95, 0x41, 0x0f, 0x1c, 0x40, 0x53, 0xe0, 0xc4, 0x25, 0x72, 0x1d,
	0xd3, 0x5a, 0x59, 0xec, 0x28, 0x76, 0xa7, 0xe5, 0x5f, 0xf0, 0x3b, 0x90, 0xf8, 0x1f, 0x3b, 0xee,
	0x82, 0xc4, 0x09, 0x50, 0xfb, 0x33, 0xb8, 0x20, 0x3b, 0x76, 0xda, 0xa1, 0x5d, 0x90, 0x38, 0xf5,
	0xe9, 0xf3, 0xe7, 0xf7, 0xea, 0xe7, 0xe7, 0x80, 0xdb, 0x39, 0x2a, 0x3f, 0xd1, 0x50, 0x96, 0x39,
	0x11, 0x41, 0x5e, 0x70, 0xc9, 0x3d, 0x98, 0x52, 0x8a, 0x17, 0x88, 0xb2, 0xc0, 0x06, 0x93, 0x40,
	0x5b, 0x07, 0x3e, 0xe6, 0x22, 0xe3, 0x22, 0x9c, 0x21, 0x41, 0xc2, 0xb3, 0xf1, 0x8c, 0x48, 0x34,
	0x0e, 0x31, 0xa7, 0xac, 0xda, 0x79, 0xb0, 0x3f, 0xe7, 0x73, 0xae, 0xc3, 0x50, 0x45, 0x15, 0x1d,
	0x7e, 0x75, 0x41, 0xfb, 0x2d, 0x29, 0xf0, 0x02, 0x31, 0xe9, 0x3d, 0x06, 0xb7, 0x32, 0x13, 0xc7,
	0x28, 0x49, 0x0a, 0x22, 0x04, 0x74, 0x06, 0xce, 0xa8, 0x13, 0xf5, 0x2d, 0x7f, 0x59, 0x61, 0xef,
	0x11, 0xe8, 0xe3, 0x82, 0x20, 0xc9, 0x8b, 0xda, 0xbc, 0xa1, 0xcd, 0x9e, 0xc1, 0x56, 0x7c, 0x08,
	0xf6, 0x66, 0x4b, 0x41, 0x19, 0x11, 0x22, 0x66, 0x28, 0x23, 0xd0, 0xd5, 0x5a, 0xd7, 0xc2, 0x77,
	0x28, 0x23, 0xaa, 0x70, 0x2d, 0xd9, 0x74, 0xcd, 0xaa, 0xb0, 0xe5, 0x36, 0xdf, 0x11, 0xe8, 0xd5,
	0x6a, 0xbe, 0xe0, 0x8c, 0xc0, 0x1d, 0x2d, 0xd6, 0x55, 0x4e, 0x14, 0xbc, 0xa2, 0x91, 0x0c, 0xd1,
	0x53, 0xd8, 0xba, 0xaa, 0x4d, 0x15, 0xf4, 0xc6, 0x60, 0xbf, 0xd6, 0x12, 0x22, 0x70, 0x41, 0x73,
	0x49, 0x39, 0x83, 0xbb, 0x5a, 0xbe, 0x63, 0xd7, 0x5e, 0x6f, 0x96, 0xbc, 0x07, 0x00, 0xa4, 0x25,
	0x8e, 0x85, 0x44, 0x72, 0x29, 0x60, 0x7b, 0xe0, 0x8c, 0xda, 0x51, 0x27, 0x2d, 0xf1, 0x7b, 0x0d,
	0xd4, 0x79, 0xd5, 0xb2, 0xa4, 0x19, 0x11, 0x12, 0x65, 0x39, 0xec, 0x0c, 0x9c, 0x91, 0x1b, 0x75,
	0xd3, 0x12, 0x7f, 0xb0, 0xcc, 0x7b, 0x01, 0xa0, 0x92, 0xc8, 0x79, 0x4e, 0x0b, 0xa4, 0xb2, 0x6e,
	0xf9, 0x40, 0xfb, 0x77, 0xd3, 0x12, 0x4f, 0xeb, 0xe5, 0x7a, 0xe7, 0xf0, 0x9b, 0x03, 0xfa, 0xf6,
	0xbe, 0x22, 0x72, 0x46, 0xd8, 0x92, 0xfc, 0xcb, 0xb5, 0x1d, 0x81, 0x9e, 0xe4, 0x12, 0x9d, 0xc6,
	0x39, 0x2a, 0x33, 0xc2, 0x64, 0x75, 0x6b, 0xcd, 0x68, 0x4f, 0xd3, 0x13, 0x03, 0xbd, 0x1c, 0x54,
	0x20, 0x2e, 0xaa, 0x12, 0xd0, 0x1d, 0xb8, 0xa3, 0x9b, 0xcf, 0xef, 0x05, 0xd5, 0x8c, 0x05, 0x6a,
	0xc6, 0x02, 0x33, 0x63, 0xc1, 0x2b, 0x4e, 0xd9, 0xf1, 0xb3, 0x8b, 0x1f, 0x87, 0x8d, 0x2f, 0x3f,
	0x0f, 0x47, 0x73, 0x2a, 0x17, 0xcb, 0x59, 0x80, 0x79, 0x16, 0x9a, 0x81, 0xac, 0x7e, 0x9e, 0x8a,
	0x24, 0x35, 0x93, 0xac, 0x36, 0x88, 0xa8, 0xab, 0x2b, 0x98, 0x33, 0x0c, 0x7f, 0x3b, 0x60, 0xd7,
	0x94, 0x57, 0x1d, 0x36, 0x7f, 0x2f, 0xa6, 0x89, 0x3e, 0x49, 0x33, 0xea, 0x18, 0xf2, 0x26, 0x51,
	0x1d, 0xce, 0x51, 0x49, 0xfe, 0x1e, 0xbc, 0xae, 0x86, 0xf6, 0xa0, 0xd7, 0xf5, 0xc4, 0xbd, 0xbe,
	0x27, 0xf7, 0x41, 0x67, 0xd3, 0xfd, 0xa6, 0xee, 0xfe, 0x06, 0x78, 0x18, 0xb4, 0x50, 0xc6, 0x97,
	0x4c, 0xc2, 0x9d, 0xff, 0xdf, 0x03, 0x93, 0xfa, 0x78, 0x7a, 0xb1, 0xf2, 0x9d, 0xcb, 0x95, 0xef,
	0xfc, 0x5a, 0xf9, 0xce, 0xe7, 0xb5, 0xdf, 0xb8, 0x5c, 0xfb, 0x8d, 0xef, 0x6b, 0xbf, 0xf1, 0xf1,
	0xc9, 0x56, 0x2e, 0xfb, 0xe2, 0xeb, 0x60, 0x12, 0x9e, 0x87, 0x5b, 0x9f, 0x88, 0x59, 0x4b, 0xbf,
	0xe9, 0xc9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x26, 0xe8, 0x8e, 0x85, 0x38, 0x04, 0x00, 0x00,
}

func (m *Merchant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Merchant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Merchant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KycExpirationTimestamp != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.KycExpirationTimestamp))
		i--
		dAtA[i] = 0x50
	}
	if m.KycTimestamp != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.KycTimestamp))
		i--
		dAtA[i] = 0x48
	}
	if m.KycStatus {
		i--
		if m.KycStatus {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.BusinessDescription) > 0 {
		i -= len(m.BusinessDescription)
		copy(dAtA[i:], m.BusinessDescription)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessDescription)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.BusinessEmail) > 0 {
		i -= len(m.BusinessEmail)
		copy(dAtA[i:], m.BusinessEmail)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessEmail)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BusinessPhone) > 0 {
		i -= len(m.BusinessPhone)
		copy(dAtA[i:], m.BusinessPhone)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessPhone)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BusinessAddress) > 0 {
		i -= len(m.BusinessAddress)
		copy(dAtA[i:], m.BusinessAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BusinessName) > 0 {
		i -= len(m.BusinessName)
		copy(dAtA[i:], m.BusinessName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CreatorAddress) > 0 {
		i -= len(m.CreatorAddress)
		copy(dAtA[i:], m.CreatorAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MerchantRevenue) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MerchantRevenue) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MerchantRevenue) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TotalRevenue) > 0 {
		for iNdEx := len(m.TotalRevenue) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TotalRevenue[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.TotalPayments != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TotalPayments))
		i--
		dAtA[i] = 0x10
	}
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Payment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Payment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Payment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTypes(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Timestamp != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.PayerAddress) > 0 {
		i -= len(m.PayerAddress)
		copy(dAtA[i:], m.PayerAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.PayerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.PaymentId != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PaymentId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Merchant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CreatorAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessPhone)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessEmail)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessDescription)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.KycStatus {
		n += 2
	}
	if m.KycTimestamp != 0 {
		n += 1 + sovTypes(uint64(m.KycTimestamp))
	}
	if m.KycExpirationTimestamp != 0 {
		n += 1 + sovTypes(uint64(m.KycExpirationTimestamp))
	}
	return n
}

func (m *MerchantRevenue) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.TotalPayments != 0 {
		n += 1 + sovTypes(uint64(m.TotalPayments))
	}
	if len(m.TotalRevenue) > 0 {
		for _, e := range m.TotalRevenue {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func (m *Payment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PaymentId != 0 {
		n += 1 + sovTypes(uint64(m.PaymentId))
	}
	l = len(m.PayerAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovTypes(uint64(m.Timestamp))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTypes(uint64(l))
		}
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Merchant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Merchant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Merchant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessPhone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessPhone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessEmail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessEmail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KycStatus", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.KycStatus = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KycTimestamp", wireType)
			}
			m.KycTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KycTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KycExpirationTimestamp", wireType)
			}
			m.KycExpirationTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.KycExpirationTimestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MerchantRevenue) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MerchantRevenue: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MerchantRevenue: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPayments", wireType)
			}
			m.TotalPayments = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalPayments |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRevenue", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TotalRevenue = append(m.TotalRevenue, types.Coin{})
			if err := m.TotalRevenue[len(m.TotalRevenue)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Payment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Payment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Payment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentId", wireType)
			}
			m.PaymentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaymentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
