// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: payfi/types.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Merchant represents a registered merchant in the system
type Merchant struct {
	MerchantAddress     string `protobuf:"bytes,1,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	CreatorAddress      string `protobuf:"bytes,2,opt,name=creator_address,json=creatorAddress,proto3" json:"creator_address,omitempty"`
	BusinessName        string `protobuf:"bytes,3,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	BusinessAddress     string `protobuf:"bytes,4,opt,name=business_address,json=businessAddress,proto3" json:"business_address,omitempty"`
	BusinessPhone       string `protobuf:"bytes,5,opt,name=business_phone,json=businessPhone,proto3" json:"business_phone,omitempty"`
	BusinessEmail       string `protobuf:"bytes,6,opt,name=business_email,json=businessEmail,proto3" json:"business_email,omitempty"`
	BusinessDescription string `protobuf:"bytes,7,opt,name=business_description,json=businessDescription,proto3" json:"business_description,omitempty"`
	KycStatus           bool   `protobuf:"varint,8,opt,name=kyc_status,json=kycStatus,proto3" json:"kyc_status,omitempty"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc3a40c559a2ead8, []int{0}
}
func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return m.Size()
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

func (m *Merchant) GetCreatorAddress() string {
	if m != nil {
		return m.CreatorAddress
	}
	return ""
}

func (m *Merchant) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *Merchant) GetBusinessAddress() string {
	if m != nil {
		return m.BusinessAddress
	}
	return ""
}

func (m *Merchant) GetBusinessPhone() string {
	if m != nil {
		return m.BusinessPhone
	}
	return ""
}

func (m *Merchant) GetBusinessEmail() string {
	if m != nil {
		return m.BusinessEmail
	}
	return ""
}

func (m *Merchant) GetBusinessDescription() string {
	if m != nil {
		return m.BusinessDescription
	}
	return ""
}

func (m *Merchant) GetKycStatus() bool {
	if m != nil {
		return m.KycStatus
	}
	return false
}

func init() {
	proto.RegisterType((*Merchant)(nil), "kiichain.kiichain3.payfi.Merchant")
}

func init() { proto.RegisterFile("payfi/types.proto", fileDescriptor_dc3a40c559a2ead8) }

var fileDescriptor_dc3a40c559a2ead8 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xc1, 0x4e, 0xc2, 0x30,
	0x1c, 0xc6, 0x19, 0x2a, 0x42, 0xa3, 0xa0, 0x93, 0x43, 0x43, 0x62, 0x43, 0x34, 0x46, 0x8c, 0xc9,
	0x1a, 0xc2, 0x13, 0x68, 0xe4, 0xa8, 0x31, 0x78, 0xf3, 0x42, 0xba, 0x52, 0x59, 0x83, 0x6b, 0x97,
	0xfd, 0x8b, 0x71, 0x6f, 0xe1, 0x63, 0x79, 0x32, 0x1c, 0x3d, 0x1a, 0xf6, 0x22, 0x66, 0x1d, 0x9d,
	0x72, 0xfb, 0xf2, 0xeb, 0xaf, 0xff, 0xef, 0xf0, 0xa1, 0xe3, 0x84, 0x65, 0x2f, 0x92, 0x9a, 0x2c,
	0x11, 0x10, 0x24, 0xa9, 0x36, 0xda, 0xc7, 0x0b, 0x29, 0x79, 0xc4, 0xa4, 0x0a, 0x5c, 0x18, 0x05,
	0xd6, 0xea, 0x11, 0xae, 0x21, 0xd6, 0x40, 0x43, 0x06, 0x82, 0xbe, 0x0d, 0x43, 0x61, 0xd8, 0x90,
	0x72, 0x2d, 0x55, 0xf9, 0xb3, 0xd7, 0x9d, 0xeb, 0xb9, 0xb6, 0x91, 0x16, 0xa9, 0xa4, 0x67, 0x5f,
	0x75, 0xd4, 0xbc, 0x17, 0x29, 0x8f, 0x98, 0x32, 0xfe, 0x15, 0x3a, 0x8a, 0x37, 0x79, 0xca, 0x66,
	0xb3, 0x54, 0x00, 0x60, 0xaf, 0xef, 0x0d, 0x5a, 0x93, 0x8e, 0xe3, 0x37, 0x25, 0xf6, 0x2f, 0x51,
	0x87, 0xa7, 0x82, 0x19, 0x9d, 0x56, 0x66, 0xdd, 0x9a, 0xed, 0x0d, 0x76, 0xe2, 0x39, 0x3a, 0x0c,
	0x97, 0x20, 0x95, 0x00, 0x98, 0x2a, 0x16, 0x0b, 0xbc, 0x63, 0xb5, 0x03, 0x07, 0x1f, 0x58, 0x2c,
	0x8a, 0xe2, 0x4a, 0x72, 0xe7, 0x76, 0xcb, 0x62, 0xc7, 0xdd, 0xbd, 0x0b, 0xd4, 0xae, 0xd4, 0x24,
	0xd2, 0x4a, 0xe0, 0x3d, 0x2b, 0x56, 0x2d, 0x8f, 0x05, 0xdc, 0xd2, 0x44, 0xcc, 0xe4, 0x2b, 0x6e,
	0x6c, 0x6b, 0xe3, 0x02, 0xfa, 0x43, 0xd4, 0xad, 0xb4, 0x99, 0x00, 0x9e, 0xca, 0xc4, 0x48, 0xad,
	0xf0, 0xbe, 0x95, 0x4f, 0xdc, 0xdb, 0xdd, 0xdf, 0x93, 0x7f, 0x8a, 0xd0, 0x22, 0xe3, 0x53, 0x30,
	0xcc, 0x2c, 0x01, 0x37, 0xfb, 0xde, 0xa0, 0x39, 0x69, 0x2d, 0x32, 0xfe, 0x64, 0xc1, 0xed, 0xf8,
	0x73, 0x4d, 0xbc, 0xd5, 0x9a, 0x78, 0x3f, 0x6b, 0xe2, 0x7d, 0xe4, 0xa4, 0xb6, 0xca, 0x49, 0xed,
	0x3b, 0x27, 0xb5, 0xe7, 0xeb, 0xb9, 0x34, 0xd1, 0x32, 0x0c, 0xb8, 0x8e, 0xa9, 0x1b, 0xaf, 0x0a,
	0x23, 0xfa, 0x4e, 0xff, 0xad, 0x1d, 0x36, 0xec, 0x3c, 0xa3, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x3b, 0x6b, 0x36, 0xd5, 0x03, 0x02, 0x00, 0x00,
}

func (m *Merchant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Merchant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Merchant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.KycStatus {
		i--
		if m.KycStatus {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if len(m.BusinessDescription) > 0 {
		i -= len(m.BusinessDescription)
		copy(dAtA[i:], m.BusinessDescription)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessDescription)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.BusinessEmail) > 0 {
		i -= len(m.BusinessEmail)
		copy(dAtA[i:], m.BusinessEmail)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessEmail)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BusinessPhone) > 0 {
		i -= len(m.BusinessPhone)
		copy(dAtA[i:], m.BusinessPhone)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessPhone)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BusinessAddress) > 0 {
		i -= len(m.BusinessAddress)
		copy(dAtA[i:], m.BusinessAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BusinessName) > 0 {
		i -= len(m.BusinessName)
		copy(dAtA[i:], m.BusinessName)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.BusinessName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.CreatorAddress) > 0 {
		i -= len(m.CreatorAddress)
		copy(dAtA[i:], m.CreatorAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.CreatorAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Merchant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.CreatorAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessName)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessAddress)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessPhone)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessEmail)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.BusinessDescription)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	if m.KycStatus {
		n += 2
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Merchant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Merchant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Merchant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessPhone", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessPhone = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessEmail", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessEmail = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessDescription", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessDescription = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field KycStatus", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.KycStatus = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
