syntax = "proto3";
package kiichain.kiichain3.payfi;

import "cosmos/base/v1beta1/coin.proto";
import "gogoproto/gogo.proto";

option go_package = "github.com/kiichain/kiichain3/x/payfi/types";

// Merchant represents a registered merchant in the system
message Merchant {
  string merchant_address = 1;
  string creator_address = 2;
  string business_name = 3;
  string business_address = 4;
  string business_phone = 5;
  string business_email = 6;
  string business_description = 7;
  bool kyc_status = 8;
}
